addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.12")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"             % "1.0.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.14.10")
