name: ci
on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ openjdk@1.8, openjdk@1.11 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties')}}

      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}

      - run: sbt package-jar

      - uses: actions/upload-artifact@master
        with:
          name: reno-snapshot.jar
          path: target/scala-2.13/reno-**.jar
